more unsigned long where size_t should be used
memory_managers/array_grid.cc:549:6:   required from here
memory_managers/hole_base.h:232:13: error: cast from 'short int*' to
'long unsigned int' loses precision [-fpermissive]
   s.put_hex((unsigned long)data);
             ^~~~~~~~~~~~~~~~~~~