sizeof long and sizeof int might be same
memory_managers/freelists.cc: In member function 'virtual
MEDDLY::memory_manager* MEDDLY::freelist_style::initManager(unsigned
char, unsigned char, MEDDLY::memstats&) const':
memory_managers/freelists.cc:335:5: error: duplicate case value
     case sizeof(long):
     ^~~~
memory_managers/freelists.cc:332:5: note: previously used here
     case sizeof(int):
     ^~~~
memory_managers/freelists.cc: In instantiation of 'MEDDLY::node_address
MEDDLY::freelist_manager<INT>::requestChunk(size_t&) [with INT = long
int; MEDDLY::node_address = long long unsigned int; size_t = long long
unsigned int]':
memory_managers/freelists.cc:137:22:   required from here